enableOnLaunch = True
toggleKey = Home

reshadeTexturePath = /home/pol/code/shaders/gamespecific/cs2/shaders
reshadeIncludePath = /home/pol/code/shaders/gamespecific/cs2/shaders

# ── General shaders ───────────────────────────────────────────────────────────
zone_contrast  = /home/pol/code/shaders/general/olofssonian-zone-contrast/olofssonian_zone_contrast.fx
chroma_lift    = /home/pol/code/shaders/general/olofssonian-chroma-lift/olofssonian_chroma_lift.fx
color_grade    = /home/pol/code/shaders/general/color-grade/olofssonian_color_grade.fx

effects = zone_contrast:chroma_lift:color_grade
