enableOnLaunch = True
toggleKey = Home

reshadeTexturePath = /home/pol/code/shaders/gamespecific/gzw/shaders
reshadeIncludePath = /home/pol/code/shaders/gamespecific/gzw/shaders

# ── ANALYSIS ──────────────────────────────────────────────────────────────────
analysis_frame     = /home/pol/code/shaders/general/analysis-frame/analysis_frame.fx

# ── CORRECTIVE ────────────────────────────────────────────────────────────────
inverse_grade       = /home/pol/code/shaders/general/inverse-grade/inverse_grade.fx
corrective          = /home/pol/code/shaders/general/corrective/corrective.fx

# ── GRADE ─────────────────────────────────────────────────────────────────────
grade            = /home/pol/code/shaders/general/grade/grade.fx

effects = analysis_frame:inverse_grade:corrective:grade

