enableOnLaunch = True
toggleKey = Home

reshadeTexturePath = /home/pol/code/shaders/gamespecific/arc_raiders/shaders
reshadeIncludePath = /home/pol/code/shaders/gamespecific/arc_raiders/shaders

# ── ANALYSIS ──────────────────────────────────────────────────────────────────
analysis_frame_analysis = /home/pol/code/shaders/general/analysis-frame-analysis/analysis_frame_analysis.fx
analysis_scope_pre      = /home/pol/code/shaders/general/analysis-scope/analysis_scope_pre.fx
analysis_scope          = /home/pol/code/shaders/general/analysis-scope/analysis_scope.fx

# ── CORRECTIVE ────────────────────────────────────────────────────────────────
inverse_grade           = /home/pol/code/shaders/general/inverse-grade/inverse_grade.fx
corrective_render_chain = /home/pol/code/shaders/general/corrective-render-chain/corrective_render_chain.fx

# ── CREATIVE ──────────────────────────────────────────────────────────────────
creative_render_chain = /home/pol/code/shaders/general/creative-render-chain/creative_render_chain.fx
creative_color_grade = /home/pol/code/shaders/general/creative-color-grade/creative_color_grade.fx
pro_mist = /home/pol/code/shaders/general/pro-mist/pro_mist.fx
veil              = /home/pol/code/shaders/general/veil/veil.fx
retinal_vignette  = /home/pol/code/shaders/general/retinal-vignette/retinal_vignette.fx

effects = analysis_frame_analysis:inverse_grade:analysis_scope_pre:corrective_render_chain:creative_render_chain:creative_color_grade:pro_mist:analysis_scope
